### ISSUE TITLE
GUI causes ping spikes on Mac when using WiFi

### ISSUE THREAD

**Issue by leojonathanoh** [synergy/synergy#4520]
On OSX 10.10.3, when synergy 1.6.3 isn't started, pinging my LAN router on wifi (wireless AC) is normal (1ms pings without spikes at all). However once synergy client is started, without even connecting to the synergy server, ping spikes are seen every 10 seconds, with spikes ranging from 50ms going up to 150ms for about 3 seconds; 10 seconds later the spikes are seen again for 3 seconds -- these spikes are correlated with 8%-25% CPU usage by the Synergy in Activity Monitor. Closing synergy at this point and no more spikes are seen. 
Moreover, a NAT client behind this OSX machine sees the exact same pattern of ping spikes (also about 50-150ms) when synergy is open, and no ping spikes when synergy is killed.

**Comment by jgoldschrafe** [comment]
I'm seeing this exact same behavior on the 1.7.0 beta I just downloaded. I only noticed it because the mouse gets really choppy as the network becomes saturated.

**Comment by jgoldschrafe** [comment]
I can confirm that this behavior is a regression in 1.6.3+ and does not occur in 1.6.2 or earlier versions.

**Comment by nbolton** [comment]
Does this happen when the GUI is open and in stopped mode?

**Comment by leojonathanoh** [comment]
yep, as long as synergy process is running, and regardless of whether it is started or stopped on the GUI. It's not a server-client connectivity issue.

**Comment by nbolton** [comment]
I'm pretty sure that just having the GUI open causes this (happens when client/server is stopped).

**Comment by nbolton** [comment]
@XinyuHou I suspect this is something to do with Bonjour.

**Comment by nbolton** [comment]
@XinyuHou This is absolutely caused by the GUI, no question about it. Here's 2 screenshots, the first is when Synergy GUI is not running, the second is when the GUI is running (notice the ping spike half way down).

![screen shot 2015-04-21 at 10 35 17 pm](https://cloud.githubusercontent.com/assets/313427/7263128/d58894fe-e876-11e4-849b-338b7bcf88a6.png)

![screen shot 2015-04-21 at 10 35 31 pm](https://cloud.githubusercontent.com/assets/313427/7263130/d818b35c-e876-11e4-899e-849aedce2018.png)

**Comment by XinyuHou** [comment]
@nbolton 
It is highly likely to do with Bonjour.

**Comment by XinyuHou** [comment]
@jgoldschrafe @legonigel 
Is your Mac server or client with auto configuration on?

**Comment by legonigel** [comment]
@XinyuHou I think you mean @leojonathanoh not me, I don't have a mac

**Comment by XinyuHou** [comment]
@legonigel 
Sorry, my mistake.

**Comment by XinyuHou** [comment]
@leojonathanoh 
Is your Mac server or client with auto configuration on?

**Comment by ehajri** [comment]
Same issue here.

MBP running 1.6.2 with no issues, and iMac running latest and the mouse is laggy.

downgraded to 1.6.2 and I stopped having ping spikes.

**Comment by XinyuHou** [comment]
I can confirm 1.6.2 doesn't have this problem.

**Comment by XinyuHou** [comment]
@nbolton I personally think this is caused by qt 5.4.1. Issue persists when I recompiled 1.6.2 using qt 5.4.1, while our 1.6.2 release used qt 5.2.1 which doesn't have this issue.

**Comment by nbolton** [comment]
@jakepetroules Any ideas? :)

**Comment by jakepetroules** [comment]
Am I to understand that compiling the exact same code with Qt 5.4.1 has an issue (and it only happens on OS X), while Qt 5.2.1 does not? That information, and if you can create a small test case, should make finding and resolving the issue significantly easier.

**Comment by XinyuHou** [comment]
@jakepetroules 
Yeah,Qt 5.4.1 has spike issue on my Mac 10.10.3 but Qt 5.2.1 doesn't. The main GUI part of the code is the same. I had to modify some python script, because in Synergy 1.6.2 it used hard coded Qt 5.2.1 SDK.

I tried to disable some functionality in Synergy, like IpcClient, logging system and Bonjour. but that didn't help me narrow down the causes. A fresh new GUI project doesn't have this issue. Personally I think it may be something related to the QtNetwork framework.

To reproduce the issue, just open Synergy GUI, don't need to start Synergys/c. Then you can see a ping spike every 3 to 5 seconds. Close GUI issue disappears.

**Comment by XinyuHou** [comment]
#4591 should solve this

**Comment by XinyuHou** [comment]
Fixed in 4af987e8de92d5f0a38c5ace7a683580a9e9843c

Nightly: http://synergy-project.org/nightly?filter=4af987

**Comment by markrmiller** [comment]
Awesome. This has hit me off and on forever.

**Comment by timmcd69** [comment]
This (or something very similar) is still happenening with 1.7.2 on Mac as a client, and 1.7.2 on Windows as the server.  On the Mac, the mouse cursor "hangs" for a split second 2-3 times a second as you move it around.  It seems to have nothing to do with the Synergy Mac GUI, but rather somethign to do with AirPlay.  I can almost always reproduce it by going into System Preferences > Displays.  When in there, it seems like the Mac is maybe querying the network for AirPlay devices.  This results in network lag that is clearly evident if you watch a "ping -i 0.1 <synergy server>".  After I close the Displays screen, the lag goes away.

**Comment by xdaimon** [comment]
I eventually have found that running "ping -i 0.1 server" in a terminal seems to reduce the lag. As if the wifi device on my Mac Mini (el capitan) goes to sleep. 

The above comment by timmcd69 mentions severe lag when looking in System Preferences > Displays. I too notice this lagginess in the cursor. 

I am on a wireless network unfortunately. Hopefully I can switch to a wired network soon. 

Good luck.
