### ISSUE TITLE
Settings dialog too big on Windows

### ISSUE THREAD

**Issue by nbolton** [synergy/synergy#4852]
![image](https://cloud.githubusercontent.com/assets/313427/8559964/e8df2968-24c7-11e5-85e4-58c163613b0e.png)

**Comment by XinyuHou** [comment]
Fixed by 5709995f79d2651d1a15a9c5af137b0d8fabfb6a

**Comment by nbolton** [comment]
Still not fixed.
![image](https://cloud.githubusercontent.com/assets/313427/8865016/b2ae3058-315d-11e5-856c-91605ba26da4.png)

**Comment by nbolton** [comment]
Sorry, wrong version!
